apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-week7
data:
  APP_NAME: "DevOps Week 7 App"
  APP_ENV: "development"
  GREETING_MESSAGE: "Hello from a ConfigMap-driven config!"
